"use client";

import { StudioCanvasHeader } from "./StudioCanvasHeader";
import { StudioCanvasNotices } from "./StudioCanvasNotices";
import { StudioFlowDetailModal } from "./StudioFlowDetailModal";
import { StudioWorkflowOverview } from "./StudioWorkflowOverview";
import { useStudioCanvasState } from "./useStudioCanvasState";

export function StudioCanvas() {
  const {
    missionGoal,
    setMissionGoal,
    missionBudget,
    setMissionBudget,
    useMockRuntime,
    setUseMockRuntime,
    isExecuting,
    executeError,
    draftSavedAt,
    draftNotice,
    showFlowModal,
    flowModalTab,
    setFlowModalTab,
    showAddPanel,
    setShowAddPanel,
    linkTargetId,
    setLinkTargetId,
    loopBandMode,
    setLoopBandMode,
    setBandSelectedNodeIds,
    addContextLabel,
    isDemoMode,
    hiredAgents,
    nodes,
    edges,
    loopRegions,
    setSelectedLoopRegionId,
    removeLoopRegion,
    selectedNodeId,
    setSelectedNodeId,
    missionRunTransitionWarning,
    clearMissionRunTransitionWarning,
    nodeExecutionStates,
    orderedFlowNodes,
    stepIndexByNodeId,
    selectLoopRegionForEdit,
    selectedNode,
    selectedNodeData,
    selectedNodeLabel,
    selectedConditionMode,
    selectedConditionDsl,
    selectedApprovalChannels,
    approvalChannelStates,
    selectedUnreadyApprovalChannels,
    linkableTargetNodes,
    selectedLoopRegion,
    bandSelectedNodes,
    bandSelectedNodeIdSet,
    bandSelectedEdges,
    selectedLoopNodes,
    outsideLoopNodes,
    selectedLoopStartNode,
    selectedLoopEndNode,
    selectedLoopConditionNodeId,
    selectedLoopConditionNode,
    selectedLoopExitNode,
    conditionNodes,
    activeConditionNode,
    setSelectedConditionNodeId,
    activeConditionData,
    conditionBranches,
    activeConditionDsl,
    conditionTargetNodes,
    libraryOnlyAgents,
    approvalGateCount,
    conditionRuleCount,
    runReadiness,
    openFlowModal,
    closeFlowModal,
    appendAgentToFlow,
    appendUtilityToFlow,
    connectSelectedToTarget,
    updateSelectedNodeData,
    updateSelectedConditionMode,
    toggleSelectedApprovalChannel,
    toggleLoopBandNode,
    createLoopRegionFromBand,
    updateSelectedLoopRegion,
    updateConditionNodeData,
    addConditionNode,
    addConditionBranch,
    updateConditionBranch,
    removeConditionBranch,
    applyConditionBranchConnection,
    handleSaveDraft,
    handleRestoreDraft,
    handleDiscardDraft,
    handleClearCanvas,
    handleExecute
  } = useStudioCanvasState();
  return (
    <div className="studio-grid-bg flex min-h-[720px] min-w-0 flex-1 flex-col lg:min-h-0">
      <StudioCanvasHeader
        missionGoal={missionGoal}
        setMissionGoal={setMissionGoal}
        missionBudget={missionBudget}
        setMissionBudget={setMissionBudget}
        useMockRuntime={useMockRuntime}
        setUseMockRuntime={setUseMockRuntime}
        isExecuting={isExecuting}
        isDemoMode={isDemoMode}
        nodeCount={nodes.length}
        edgeCount={edges.length}
        loopCount={loopRegions.length}
        approvalGateCount={approvalGateCount}
        conditionRuleCount={conditionRuleCount}
        runReadiness={runReadiness}
        setShowAddPanel={setShowAddPanel}
        openFlowModal={openFlowModal}
        handleClearCanvas={handleClearCanvas}
        handleSaveDraft={handleSaveDraft}
        handleExecute={handleExecute}
      />
      <StudioCanvasNotices
        missionRunTransitionWarning={missionRunTransitionWarning}
        clearMissionRunTransitionWarning={clearMissionRunTransitionWarning}
        executeError={executeError}
        draftSavedAt={draftSavedAt}
        draftNotice={draftNotice}
        handleRestoreDraft={handleRestoreDraft}
        handleDiscardDraft={handleDiscardDraft}
      />

      <StudioWorkflowOverview
        showAddPanel={showAddPanel}
        setShowAddPanel={setShowAddPanel}
        addContextLabel={addContextLabel}
        hiredAgents={hiredAgents}
        libraryOnlyAgents={libraryOnlyAgents}
        appendAgentToFlow={appendAgentToFlow}
        appendUtilityToFlow={appendUtilityToFlow}
        orderedFlowNodes={orderedFlowNodes}
        nodeExecutionStates={nodeExecutionStates}
        selectedNodeId={selectedNodeId}
        setSelectedNodeId={setSelectedNodeId}
        nodes={nodes}
        edges={edges}
        loopRegions={loopRegions}
        selectLoopRegionForEdit={selectLoopRegionForEdit}
        openFlowModal={openFlowModal}
      />
      <StudioFlowDetailModal
        showFlowModal={showFlowModal}
        addContextLabel={addContextLabel}
        loopBandMode={loopBandMode}
        setFlowModalTab={setFlowModalTab}
        setLoopBandMode={setLoopBandMode}
        setBandSelectedNodeIds={setBandSelectedNodeIds}
        handleSaveDraft={handleSaveDraft}
        closeFlowModal={closeFlowModal}
        flowModalTab={flowModalTab}
        nodes={nodes}
        edges={edges}
        loopRegions={loopRegions}
        bandSelectedNodes={bandSelectedNodes}
        bandSelectedEdges={bandSelectedEdges}
        createLoopRegionFromBand={createLoopRegionFromBand}
        orderedFlowNodes={orderedFlowNodes}
        nodeExecutionStates={nodeExecutionStates}
        selectedNodeId={selectedNodeId}
        bandSelectedNodeIdSet={bandSelectedNodeIdSet}
        toggleLoopBandNode={toggleLoopBandNode}
        setSelectedNodeId={setSelectedNodeId}
        selectedNode={selectedNode}
        selectedNodeData={selectedNodeData}
        selectedNodeLabel={selectedNodeLabel}
        linkTargetId={linkTargetId}
        setLinkTargetId={setLinkTargetId}
        linkableTargetNodes={linkableTargetNodes}
        connectSelectedToTarget={connectSelectedToTarget}
        selectedConditionMode={selectedConditionMode}
        updateSelectedConditionMode={updateSelectedConditionMode}
        updateSelectedNodeData={updateSelectedNodeData}
        selectedApprovalChannels={selectedApprovalChannels}
        toggleSelectedApprovalChannel={toggleSelectedApprovalChannel}
        approvalChannelStates={approvalChannelStates}
        selectedUnreadyApprovalChannels={selectedUnreadyApprovalChannels}
        selectedConditionDsl={selectedConditionDsl}
        selectLoopRegionForEdit={selectLoopRegionForEdit}
        selectedLoopRegion={selectedLoopRegion}
        setSelectedLoopRegionId={setSelectedLoopRegionId}
        stepIndexByNodeId={stepIndexByNodeId}
        selectedLoopNodes={selectedLoopNodes}
        selectedLoopStartNode={selectedLoopStartNode}
        selectedLoopEndNode={selectedLoopEndNode}
        selectedLoopConditionNodeId={selectedLoopConditionNodeId}
        updateSelectedLoopRegion={updateSelectedLoopRegion}
        outsideLoopNodes={outsideLoopNodes}
        selectedLoopConditionNode={selectedLoopConditionNode}
        selectedLoopExitNode={selectedLoopExitNode}
        removeLoopRegion={removeLoopRegion}
        conditionNodes={conditionNodes}
        activeConditionNode={activeConditionNode}
        setSelectedConditionNodeId={setSelectedConditionNodeId}
        activeConditionData={activeConditionData}
        updateConditionNodeData={updateConditionNodeData}
        activeConditionDsl={activeConditionDsl}
        conditionBranches={conditionBranches}
        addConditionNode={addConditionNode}
        addConditionBranch={addConditionBranch}
        updateConditionBranch={updateConditionBranch}
        removeConditionBranch={removeConditionBranch}
        conditionTargetNodes={conditionTargetNodes}
        applyConditionBranchConnection={applyConditionBranchConnection}
        hiredAgents={hiredAgents}
        appendAgentToFlow={appendAgentToFlow}
        appendUtilityToFlow={appendUtilityToFlow}
      />
    </div>
  );
}

